# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'switch_screenVldrnS.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QHBoxLayout, QLabel, QPushButton,
    QSizePolicy, QStackedWidget, QWidget)

class Ui_StackedWidget(object):
    def setupUi(self, StackedWidget):
        if not StackedWidget.objectName():
            StackedWidget.setObjectName(u"StackedWidget")
        StackedWidget.resize(800, 460)
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.label = QLabel(self.page)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 20, 800, 40))
        self.label.setMaximumSize(QSize(800, 100))
        font = QFont()
        font.setFamilies([u"Segoe UI"])
        font.setPointSize(16)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet(u"background-color: #007A39; color: white;")
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_2 = QLabel(self.page)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 10, 121, 61))
        font1 = QFont()
        font1.setPointSize(12)
        font1.setBold(True)
        self.label_2.setFont(font1)
        self.label_2.setStyleSheet(u"background-color: #00A336; color: white; border: 1px solid grey;")
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.horizontalLayoutWidget_2 = QWidget(self.page)
        self.horizontalLayoutWidget_2.setObjectName(u"horizontalLayoutWidget_2")
        self.horizontalLayoutWidget_2.setGeometry(QRect(20, 180, 761, 80))
        self.horizontalLayout_2 = QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.button_model_c = QPushButton(self.horizontalLayoutWidget_2)
        self.button_model_c.setObjectName(u"button_model_c")
        self.button_model_c.setMaximumSize(QSize(400, 75))
        self.button_model_c.setFont(font1)
        self.button_model_c.setStyleSheet(u"background-color: #008000; color: white;")

        self.horizontalLayout_2.addWidget(self.button_model_c)

        self.button_model_d = QPushButton(self.horizontalLayoutWidget_2)
        self.button_model_d.setObjectName(u"button_model_d")
        self.button_model_d.setMaximumSize(QSize(400, 75))
        self.button_model_d.setFont(font1)
        self.button_model_d.setStyleSheet(u"background-color: #008000; color: white;")

        self.horizontalLayout_2.addWidget(self.button_model_d)

        self.horizontalLayoutWidget = QWidget(self.page)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(20, 90, 761, 80))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.button_model_a = QPushButton(self.horizontalLayoutWidget)
        self.button_model_a.setObjectName(u"button_model_a")
        self.button_model_a.setMaximumSize(QSize(400, 75))
        self.button_model_a.setFont(font1)
        self.button_model_a.setStyleSheet(u"background-color: #008000; color: white;")

        self.horizontalLayout.addWidget(self.button_model_a)

        self.button_model_b = QPushButton(self.horizontalLayoutWidget)
        self.button_model_b.setObjectName(u"button_model_b")
        self.button_model_b.setMaximumSize(QSize(400, 75))
        self.button_model_b.setFont(font1)
        self.button_model_b.setStyleSheet(u"background-color: #008000; color: white;")

        self.horizontalLayout.addWidget(self.button_model_b)

        self.horizontalLayoutWidget_3 = QWidget(self.page)
        self.horizontalLayoutWidget_3.setObjectName(u"horizontalLayoutWidget_3")
        self.horizontalLayoutWidget_3.setGeometry(QRect(20, 270, 761, 80))
        self.horizontalLayout_3 = QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.button_model_e = QPushButton(self.horizontalLayoutWidget_3)
        self.button_model_e.setObjectName(u"button_model_e")
        self.button_model_e.setMaximumSize(QSize(400, 75))
        self.button_model_e.setFont(font1)
        self.button_model_e.setStyleSheet(u"background-color: #008000; color: white;")

        self.horizontalLayout_3.addWidget(self.button_model_e)

        self.button_model_f = QPushButton(self.horizontalLayoutWidget_3)
        self.button_model_f.setObjectName(u"button_model_f")
        self.button_model_f.setMaximumSize(QSize(400, 75))
        self.button_model_f.setFont(font1)
        self.button_model_f.setStyleSheet(u"background-color: #008000; color: white;")

        self.horizontalLayout_3.addWidget(self.button_model_f)

        self.button_switch_screen = QPushButton(self.page)
        self.button_switch_screen.setObjectName(u"button_switch_screen")
        self.button_switch_screen.setGeometry(QRect(700, 410, 75, 24))
        font2 = QFont()
        font2.setPointSize(18)
        font2.setBold(True)
        self.button_switch_screen.setFont(font2)
        self.button_switch_screen.setStyleSheet(u"background-color: transparent;")
        StackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.horizontalLayoutWidget_5 = QWidget(self.page_2)
        self.horizontalLayoutWidget_5.setObjectName(u"horizontalLayoutWidget_5")
        self.horizontalLayoutWidget_5.setGeometry(QRect(20, 80, 761, 80))
        self.horizontalLayout_8 = QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.button_model_a_3 = QPushButton(self.horizontalLayoutWidget_5)
        self.button_model_a_3.setObjectName(u"button_model_a_3")
        self.button_model_a_3.setMaximumSize(QSize(400, 75))
        self.button_model_a_3.setFont(font1)
        self.button_model_a_3.setStyleSheet(u"background-color: #008000; color: white;")

        self.horizontalLayout_8.addWidget(self.button_model_a_3)

        self.button_model_b_3 = QPushButton(self.horizontalLayoutWidget_5)
        self.button_model_b_3.setObjectName(u"button_model_b_3")
        self.button_model_b_3.setMaximumSize(QSize(400, 75))
        self.button_model_b_3.setFont(font1)
        self.button_model_b_3.setStyleSheet(u"background-color: #008000; color: white;")

        self.horizontalLayout_8.addWidget(self.button_model_b_3)

        self.horizontalLayoutWidget_4 = QWidget(self.page_2)
        self.horizontalLayoutWidget_4.setObjectName(u"horizontalLayoutWidget_4")
        self.horizontalLayoutWidget_4.setGeometry(QRect(20, 180, 761, 80))
        self.horizontalLayout_7 = QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.button_model_c_3 = QPushButton(self.horizontalLayoutWidget_4)
        self.button_model_c_3.setObjectName(u"button_model_c_3")
        self.button_model_c_3.setMaximumSize(QSize(400, 75))
        self.button_model_c_3.setFont(font1)
        self.button_model_c_3.setStyleSheet(u"background-color: #008000; color: white;")

        self.horizontalLayout_7.addWidget(self.button_model_c_3)

        self.button_model_d_3 = QPushButton(self.horizontalLayoutWidget_4)
        self.button_model_d_3.setObjectName(u"button_model_d_3")
        self.button_model_d_3.setMaximumSize(QSize(400, 75))
        self.button_model_d_3.setFont(font1)
        self.button_model_d_3.setStyleSheet(u"background-color: #008000; color: white;")

        self.horizontalLayout_7.addWidget(self.button_model_d_3)

        self.label_3 = QLabel(self.page_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(0, 20, 800, 40))
        self.label_3.setMaximumSize(QSize(800, 100))
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(u"background-color: #007A39; color: white;")
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_4 = QLabel(self.page_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 10, 121, 61))
        self.label_4.setFont(font1)
        self.label_4.setStyleSheet(u"background-color: #00A336; color: white; border: 1px solid grey;")
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.button_switch_screen_2 = QPushButton(self.page_2)
        self.button_switch_screen_2.setObjectName(u"button_switch_screen_2")
        self.button_switch_screen_2.setGeometry(QRect(720, 410, 75, 24))
        self.button_switch_screen_2.setFont(font2)
        self.button_switch_screen_2.setStyleSheet(u"background-color: transparent;")
        StackedWidget.addWidget(self.page_2)

        self.retranslateUi(StackedWidget)


        QMetaObject.connectSlotsByName(StackedWidget)
    # setupUi

    def retranslateUi(self, StackedWidget):
        StackedWidget.setWindowTitle(QCoreApplication.translate("StackedWidget", u"StackedWidget", None))
#if QT_CONFIG(statustip)
        self.label.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.label.setText(QCoreApplication.translate("StackedWidget", u"ESCOLHA O MODELO SWITCH PARA O TESTE", None))
#if QT_CONFIG(statustip)
        self.label_2.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.label_2.setText(QCoreApplication.translate("StackedWidget", u"INTELBRAS", None))
#if QT_CONFIG(statustip)
        self.horizontalLayoutWidget_2.setStatusTip("")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.button_model_c.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.button_model_c.setText(QCoreApplication.translate("StackedWidget", u"Key Switch", None))
#if QT_CONFIG(statustip)
        self.button_model_d.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.button_model_d.setText(QCoreApplication.translate("StackedWidget", u"Push Button Switch", None))
#if QT_CONFIG(statustip)
        self.horizontalLayoutWidget.setStatusTip("")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.button_model_a.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.button_model_a.setText(QCoreApplication.translate("StackedWidget", u"Toggle Switch", None))
#if QT_CONFIG(statustip)
        self.button_model_b.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.button_model_b.setText(QCoreApplication.translate("StackedWidget", u"Lever Switch", None))
#if QT_CONFIG(statustip)
        self.horizontalLayoutWidget_3.setStatusTip("")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.button_model_e.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.button_model_e.setText(QCoreApplication.translate("StackedWidget", u"Dual In-line Package Switch", None))
#if QT_CONFIG(statustip)
        self.button_model_f.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.button_model_f.setText(QCoreApplication.translate("StackedWidget", u"Reed Switch", None))
#if QT_CONFIG(statustip)
        self.button_switch_screen.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.button_switch_screen.setText(QCoreApplication.translate("StackedWidget", u">", None))
        self.button_model_a_3.setText(QCoreApplication.translate("StackedWidget", u"Push Button Switch", None))
        self.button_model_b_3.setText(QCoreApplication.translate("StackedWidget", u"Tactile Switch", None))
        self.button_model_c_3.setText(QCoreApplication.translate("StackedWidget", u"Key Switch", None))
        self.button_model_d_3.setText(QCoreApplication.translate("StackedWidget", u"Push Button Switch", None))
        self.label_3.setText(QCoreApplication.translate("StackedWidget", u"ESCOLHA O MODELO SWITCH PARA O TESTE", None))
        self.label_4.setText(QCoreApplication.translate("StackedWidget", u"INTELBRAS", None))
#if QT_CONFIG(statustip)
        self.button_switch_screen_2.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.button_switch_screen_2.setText(QCoreApplication.translate("StackedWidget", u"<", None))
    # retranslateUi

